version: '3'

services:
  redisstreamer:
    build: .
    container_name: redisstreamer
    ports:
     - 8000:8000
    volumes:
      - ./redis_streamer:/src/redis_streamer
      - ./data:/src/redis_streamer/data
    environment:
      REDIS_URL: redis://redis:6379
      # DISABLE_MULTI_DEVICE_PREFIXING: "1"
      PYTHONUNBUFFERED: "1"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis_6789.conf:/usr/local/etc/redis/redis.conf
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  # a dashboard to view redis
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - '8035:8001'
