version: '3'

services:
  redisstreamer:
    build: .
    container_name: redisstreamer
    ports:
     - 8000:8000
    volumes:
      - ./redis_streamer:/src/redis_streamer
    environment:
      REDIS_URL: redis://redis:6379
      # DISABLE_MULTI_DEVICE_PREFIXING: "1"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis_6789.conf:/usr/local/etc/redis/redis.conf
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping healthcheck | grep healthcheck"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  # a dashboard to view redis
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - '8035:8001'

  redisstreamer-record:
    build: .
    container_name: redisstreamer-record
    command: -m redis_streamer.agents.record 
    volumes:
      - ./redis_streamer:/src/redis_streamer
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped